vich_uploader:
    db_driver: orm

    mappings:
            product_images:
                uri_prefix:         /uploads/images
                upload_destination: '%kernel.project_dir%/public/uploads/images'
                
            attachements:
                uri_prefix:         /uploads/attachements
                upload_destination: '%kernel.project_dir%/public/uploads/attachements'
                